app: mod-s
org: modules
# added below
service: module-dos-support
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  # role: lambda-role
  stage: modules
  timeout: 5

functions:
  module-docs-support-GET:
    handler: ./read/index.handler
    # role: arn:aws:iam::357921866167:role/service-role/module-docs-support-GET-role-q4pdyq30
    events:
      - http:
          path: /docs
          method: get
      - http:
          path: /docs/{id}
          method: get
  module-docs-support-POST:
    handler: ./create/index.handler
    # role: arn:aws:iam::357921866167:role/service-role/module-docs-support-POST-role-9co9au39
    events:
      - http: 
          path: docs
          method: post
  module-docs-support-PUT:
    handler: ./update/index.handler
    # role: arn:aws:iam::357921866167:role/service-role/module-docs-support-PUT-role-2xp4inbj
    events:
      - http:
          path: /docs/{id}
          method: put
  module-docs-support-DELETE:
    handler: ./delete/index.handler
    # role: arn:aws:iam::357921866167:role/service-role/module-docs-support-DELETE-role-0u2la27b
    events:
      - http: 
          path: /docs/{id}
          method: delete